### ISSUE TITLE
Which scanpy version you use

### ISSUE THREAD

**Issue by tlz4320** [LouisFaure/sgnfates_paper#1]
Thank you very much for your codes, it is very helpful.
And I want to use you data and code to test and hope to do similar analysis in our datasets.
However, after I download your raw data from GEO and run your code in scanpy 1.9.1, result will be a little different with your result in jupyter notebook. But our teacher want me to do same result with your result to test my environment.
Therefore, could you list the environment you use?

**Comment by tlz4320** [comment]
After I tried many times : (, I found that is leiden's version influences the result. Maybe you could tell others to use leidenalg==0.8.2 to get the same result as you did. If one uses 0.8.10(latest version) will get different results. And small differences in preprocessing, huge differences will get in further analysis.

**Comment by LouisFaure** [comment]
Hi @tlz4320, apologies for that situation, I will update the readme asap by fixing all required versions!
